# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Это тот же самый конфиг, что и config.yml, только комментарии тут на русском языке.                                                                 #
# Если вы хотите использовать этот конфиг - удалите старый, обязательно переименуйте этот в 'config.yml' и переместите в 'plugins/UltimateCheatCheck' #
# (Ну либо просто скопируйте содержимое этого файла и заменить в том конфиге, что уже существует)                                                     #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

configVersion: 1.0

# По-умолчанию доступно 'ru'(Русский), 'en'(Английский), 'ua'(Украинский) и 'hu'(Венгерский). Если вы хотите свой файл с сообщениями, у вас есть 2 варианта:
  # 1) Отредактируйте уже существующий(-е) файл(-ы).
  # 2) Создайте новый файл в папке 'lang' с именем 'messages_КОД.yml' и укажите КОД в поле 'language'.
    # P.s. Не забудьте перезагрузить плагин/конфиги чтобы изменения вступили в силу :>
language: ru

# Уведомления в чат(для игроков с /op) и в консоль об актуальной новой версии плагина.
checkUpdates: false

# Префикс для ВСЕХ сообщений отправляемых игроку. Если вы хотите сообщения без префикса - оставьте поле пустым.
messagesPrefix: '&7(&e&lUCC&7) '

CheatCheck:
  # Эффекты, накладываемые на игрока во время начала проверки.
  EffectsToSuspect:
    - BLINDNESS
  # Время, которое даётся игроку на предоставление своих контактов модератору для связи. Значение указывается в секундах.
  Timer: 300

Titles:
  StartCheckSuspectTitle: "&cПРОВЕРКА НА ЧИТЫ"
  StartCheckSuspectSubTitle: "&fСледуйте инструкциям в чате"

BossBars:
  # Bar Color: PINK, BLUE, RED, GREEN, YELLOW, WHITE, PURPLE
  # Bar Style: SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20
  SuspectBossBar:
    Text: "Проверка на читы | У вас осталось &c%timeLeft%&r сек."
    PausedText: "Проверка на читы | Пауза"
    Color: RED
    Style: SOLID
  ModerBossBar:
    Text: "Проверка для игрока &6%suspect%&r | Осталось &c%timeLeft%&r сек."
    PausedText: "Проверка для игрока &6%suspect%&r | Пауза"
    Color: GREEN
    Style: SOLID

# Автоматические наказания.
AutoPunishments:
  # Команды будут выполняться от имени консоли.
  Commands:
    # Подозреваемый покинул игру во время активной проверки на читы.
    OnSuspectQuit:
      - 'ban %suspect% Отказ от проверки (выход с игры)'
    # Подозреваемый признался в использовании стороннего ПО.
    OnSuspectConfess:
      - 'ban %suspect% Признание в использовании стороннего ПО'
    # Модератор признал подозреваемого виновным.
    OnSuspectCondemned:
      - 'ban %suspect% Вы признаны виновным в использовании стороннего ПО'
    # Время подозреваемого, на предоставление контактных данных модератору истекло.
    OnSuspect`sTimerExpired:
      - 'ban %suspect% Отказ от проверки (время истекло)'

PlayerLocks:
  SendCommands:
    # Запретить игроку использовать команды?
    Disabled: true
    # Список разрешённых команд, вне зависимости от поля "Disabled"
    AvailableCommands:
      - '/ucc contact'
      - '/ucc confess'
  SendMessages:
    # Запретить ли игроку использовать чат?
    Disabled: true
  DropItems:
    # Запретить игроку выкидывать предметы?
    Disabled: true
  PickupItems:
    # Запретить игроку поднимать предметы?
    Disabled: true
  Moving:
    # Запретить игроку перемещаться?
    Disabled: true
  Interact:
    # Запретить игроку использовать ПКМ/ЛКМ по воздуху/блокам?
    Disabled: true
  MakeDamage:
    # Запретить игроку наносить урон игрокам/мобам и так далее?
    Disabled: true
  TakeDamage:
    # Запретить получать урон от других энтити(Игроки, Мобы и так далее) по подозреваемому?
    Disabled: true
    # Воспроизводимый звук игроку при попытке нанести урон подозреваемому.
    Sound: ENTITY_ILLUSIONER_PREPARE_MIRROR