# !!! PREFIX, MESSAGE, TITLES, BOSSBARS !!!
# If you want to use minimessage, put the following text at the beginning of the line: "[minimessage] ", and then the text you need
# If you use minimessage you won't be able to use legacy colors (&,§,&#), so you have to choose
# Minimessages doc: https://docs.advntr.dev/minimessage/format.html
# Web-constructor minimessages: https://webui.advntr.dev/
# !!! PREFIX, MESSAGE, TITLES, BOSSBARS !!!

configVersion: 1.0

  # By default, available 'en'(English), 'ru'(Russian), 'ua'(Ukrainian) and 'hu'(Hungarian). If you want your own message file, you have 2 options:
  # 1) Edit existing file(s).
  # 2) Create a new file in the 'lang' folder with the name 'messages_CODE.yml' and specify the CODE in the 'language' field.
# P.s. Don't forget to reload the plugin/configs for the changes to take effect :>
language: en

# Notifications in chat (for players with /op) and in the console about the current new version of the plugin.
checkUpdates: false

# Prefix for ALL messages sent to the player. If you want messages without a prefix, leave the field blank.
messagesPrefix: '&7(&e&lUCC&7) '

# Experimental features. !Use at your own risk!
experimental:

  # !Unstable function!
  # If the function does not take root, it must be removed!
  # If you have an authentication plugin (For example: AuthMe, nLogin, etc.) - !DO NOT USE THIS!
  # Allows you to add an offline player to the check queue using /ucc start <nickname> -l|-later.
  # This means that if a player is offline, stands in a queue and enters the server, he will instantly be called for verification by the inspector who called the command
  # To reset the queue, you need to re-login to the server or reboot it
  #
  later-checks-enabled: false

  # More or less stable function.
  # Inspectors will not be able to call a suspect for verification if EssentialsX is installed
  # on the server, this function is enabled and the afk player is via /afk
  # The suspect can be forced by adding the “-f” or “-force” flag at the end of the command (perm ucc.start.force is required)
  afk-check: true

CheatCheck:
  # Effects applied to the player when the check begins.
  EffectsToSuspect:
    - BLINDNESS
  # The time given to the player to provide his contacts to the moderator for communication. The value is indicated in seconds.
  Timer: 300
  # Should the moderator be teleported to the game at the start of the cheat check?
  AutoTeleportModerToSuspect: false
  AutoTeleportSuspect:
    enabled: false
    to:
      world: world
      x: 0
      y: 0
      z: 0
      pitch: 0
      yaw: 0

Titles:
  StartCheckSuspectTitle: "&cCHECKING FOR CHEATS"
  StartCheckSuspectSubTitle: "&fFollow the instructions in the chat"

OnCheckStart:

  # Commands that will be executed on behalf of the console when the scan starts
  # Available placeholders: %suspect% - suspect's name, %inspector% - inspector's name
  Commands:
#    - 'example command'

BossBars:
  # Bar Color: PINK, BLUE, RED, GREEN, YELLOW, WHITE, PURPLE
  # Bar Style: SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20
  SuspectBossBar:
    Text: "CHECKING FOR CHEATS | You have &c%timeLeft%&r seconds left."
    PausedText: "CHECKING FOR CHEATS | Pause"
    Color: RED
    Style: SOLID
  ModerBossBar:
    Text: "Check for the player &6%suspect%&r | &c%timeLeft%&r seconds left."
    PausedText: "Checking for the player &6%suspect%&r | Pause"
    Color: GREEN
    Style: SOLID

# Automatic punishments.
AutoPunishments:
  # Commands will be executed on behalf of the console.
  Commands:
    # The suspect left the game during an active cheat check.
    OnSuspectQuit:
      - 'ban %suspect% Refusal of cheat check (exit from the game)'
    # The suspect admitted to using third-party software.
    OnSuspectConfess:
      - 'ban %suspect% Confession of using cheats'
    # The moderator found the suspect guilty.
    OnSuspectCondemned:
      - 'ban %suspect% You have been found guilty of using cheats'
    # The moderator found the suspect not guilty.
    OnSuspectAcquitted:
#      - 'example'
    # The suspect's time to provide contact information to the moderator has expired.
    OnSuspect`sTimerExpired:
      - 'ban %suspect% Refusal of cheat check (timer expired)'

# "none" - mute sound. (Case is not important, possible: NONE, nOnE, None, NonE etc.)
Sounds:
  OnCheatCheckStarted: BLOCK_ANVIL_LAND
  OnSuspectAcquitted: BLOCK_ANVIL_LAND

PlayerLocks:
  SendCommands:
    # Prevent a player from using commands?
    Disabled: true
    # List of allowed commands, regardless of the "Disabled" field
    AvailableCommands:
#      - '/example'
  SendMessages:
    # Should I prevent a player from using chat?
    Disabled: true
  DropItems:
    # Prevent the player from throwing away items?
    Disabled: true
  PickupItems:
    # Prevent the player from picking up objects?
    Disabled: true
  Moving:
    # Prevent the player from moving?
    Disabled: true
  Interact:
    # Prohibit the player from using RMB/LMB in the air/blocks?
    Disabled: true
  MakeDamage:
    # Prevent the player from causing damage to players/mobs, etc.?
    Disabled: true
  TakeDamage:
    # Prohibit the suspect from receiving damage from other entities (Players, Mobs, etc.)?
    Disabled: true