name: UltimateCheatCheck
version: '${project.version}'
main: me.kepchyk1101.ultimatecheatcheck.UltimateCheatCheck
api-version: '1.13'
author: Kepchyk1101
website: https://github.com/Kepchyk1101/UltimateCheatCheck
loadbefore:
  - LiteBans
softdepend:
  - PlaceholderAPI
  - AntiRelog
  - Essentials
commands:
  ultimateCheatCheck:
    description: Basic command
    aliases: ucc
  confess:
    description: Confess command
permissions:
  ucc.*:
    description: Master-permission. Allows you to use any commands
    children:
      - ucc.reload
      - ucc.moder
      - ucc.start.force
  ucc.moder:
    description: Allows you to use /ucc start, /ucc acquit, /ucc condemn, /ucc pause
    children:
      - ucc.start
      - ucc.acquit
      - ucc.condemn
      - ucc.pause
      - ucc.help
  ucc.player:
    description: Allows you to use /ucc contact, /ucc confess
    default: true
    children:
      - ucc.confess
  ucc.help:
    description: Allows you to see a help window when using a command incorrectly
  ucc.immunity:
    description: Immunity to cheat checks
  ucc.reload:
    description: Allows you to use /ucc reload
  ucc.start:
    description: Allows you to use /ucc start
  ucc.start.force:
    description: Allows you to use /ucc start <nickname> -f|-force
  ucc.acquit:
    description: Allows you to use /ucc acquit
  ucc.condemn:
    description: Allows you to use /ucc condemn
  ucc.pause:
    description: Allows you to use /ucc pause
  ucc.confess:
    default: true
    description: Allows you to use /ucc confess